In [ ]:
import gdown
gdown.download('http://drive.google.com/uc?id=1BvHnDpoZfhUgjNYjHjwF4xMnk-9PrJYn','ns_book6.csv' ,quiet=False)

Downloading...
From: http://drive.google.com/uc?id=1BvHnDpoZfhUgjNYjHjwF4xMnk-9PrJYn
To: /content/ns_book6.csv
100%|██████████| 64.3M/64.3M [00:01<00:00, 35.9MB/s]

'ns_book6.csv'

###기술통계(=요약통계)
-자료의 내용을 압축하여 설명하는 방법을 말함. 정량적인 수치로 전체 데이터의 특징을 요약하거나 이해하기 쉬운 간단한 그래프를 사용함.

-대표적인 통계량 : 평균, 표준편차 등

###탐색적 데이터 분석(EDA)
-데이터 시각화를 아우르는 데이터 분석 방법

####기술통계 구하기

In [ ]:
import pandas as pd
ns_book6 = pd.read_csv('ns_book6.csv', low_memory=False)
ns_book6.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,지도와 전쟁으로 다시 읽는 한중일 세계사,이동민 지음,갈매나무,2026,9791124226087,NaN,NaN,NaN,NaN,1,0,2026-04-30
1,2,지도와 전쟁으로 다시 읽는 한중일 세계사,이동민 지음,갈매나무,2026,9791124226087,NaN,NaN,NaN,NaN,1,0,2026-04-30
2,3,흉담,전건우 지음,래빗홀,2026,9791168343764,NaN,NaN,NaN,NaN,1,0,2026-04-30
3,4,아름다움이 사람을 죽일 때,"미시마 유키오 지음, 심지애 옮김",북로드,2026,9791158792541,NaN,NaN,NaN,NaN,1,0,2026-04-30
4,5,파이로매니악 1,이우혁 지음,반타,2026,9791175772656,NaN,NaN,NaN,NaN,1,0,2026-04-30

In [ ]:
#describe() 메서드
#-기본적인 기술통계를 자동으로 추출해주는 메서드
ns_book6.describe()

'''
설명
-count : 누락된 값을 제외한 데이터 개수를 나타냄
-mean : 평균을 구함
-std : 표준편차를 구함
-min : 최솟값을 구함
-50% : 중앙값을 구함
-25% ~ 75% : 순서대로 늘어놓았을 때 25% 지점과 75% 지점에 놓인 값
-max : 최댓값을 구함
'''

'\n설명\n-count : 누락된 값을 제외한 데이터 개수를 나타냄\n-mean : 평균을 구함\n-std : 표준편차를 구함\n-min : 최솟값을 구함\n-50% : 중앙값을 구함\n-25% ~ 75% : 순서대로 늘어놓았을 때 25% 지점과 75% 지점에 놓인 값\n-max : 최댓값을 구함\n'

In [ ]:
#불리언 배열과 sum() 함수를 활용하여 도서권수가 0인 도서의 행 개수 카운트
sum(ns_book6['도서권수']==0)

0

In [ ]:
#도서권수가 0인 도서 제외
ns_book7=ns_book6[ns_book6['도서권수']>0]

In [ ]:
#describe() 메서드는 기본적으로 25%, 50%, 75% 에 위치한 값을 보여줌
#원하는 위치의 값을 보고 싶다면 percentiles 매개변수에 위치를 지정하면 됨

ns_book7.describe(percentiles=[0.3, 0.6, 0.9]) # 30%, 60%, 90%에 위치한 값을 보고싶다는 뜻

                  번호       세트 ISBN           도서권수           대출건수
count  446351.000000  5.034800e+04  446351.000000  446351.000000
mean   233776.197372  9.788106e+12       1.124310      12.993584
std    134008.403612  1.027481e+11       0.442688      20.132538
min         1.000000  8.984980e+10       1.000000       0.000000
30%    141019.000000  9.788956e+12       1.000000       3.000000
50%    236486.000000  9.788973e+12       1.000000       7.000000
60%    281874.000000  9.788981e+12       1.000000      10.000000
90%    417649.000000  9.791156e+12       2.000000      30.000000
max    464233.000000  9.791199e+12      40.000000    2287.000000

In [ ]:
#열의 데이터 타입이 수치가 아닌 다른 데이터 타입의 열의 기술통계를 보고 싶다면 include 매개변수에 데이터 타입을 지정하면 됨
ns_book7.describe(include='object')

'''
설명
-count행 : 누락된 값을 제외한 데이터 개수를 나타냄
-unique행 : 고유한 값의 개수를 나타냄
-top행 : 가장 많이 등장하는 값을 나타냄
-freq행 : top 행에 등장하는 항목의 빈도수
'''

'\n설명\n-count행 : 누락된 값을 제외한 데이터 개수를 나타냄\n-unique행 : 고유한 값의 개수를 나타냄\n-top행 : 가장 많이 등장하는 값을 나타냄\n-freq행 : top 행에 등장하는 항목의 빈도수\n'

####평균 구하기

In [ ]:
#평균을 파이썬으로 구현하기(반복문 활용)
x =[10,20,30]
sum = 0

for i in range(3):
  sum += x[i]
print("평균:", sum / len(x))

평균: 20.0

In [ ]:
#mean() 메서드 : 평균을 계산
ns_book7['대출건수'].mean()

np.float64(12.993583525073317)

####중앙값 구하기

In [ ]:
#median() 메서드
ns_book7['대출건수'].median()

7.0

In [ ]:
temp_df = pd.DataFrame([1,2,3,4])
temp_df.median()

0    2.5
dtype: float64

####중복값 제거하고 중앙값 구하기

In [ ]:
#같은 값의 대출건수를 모두 제외하고 중앙값을 계산할 수 있음
#drop_duplicates() 메서드 활용

ns_book7['대출건수'].drop_duplicates().median()

196.0

####최솟값, 최댓값 구하기

In [ ]:
#min() 메서드
ns_book7['대출건수'].min()

0

In [ ]:
#max() 메서드
ns_book7['대출건수'].max()

2287

####분위수 구하기
-분위수 : 데이터를 순서대로 늘어 놓았을 때 이를 균등한 간격으로 나누는 기준점

######ex) 이분위수는 전체 데이터를 두 구간으로 나누기 때문에 중앙값에 해당

In [ ]:
#quantile() 메서드 : 판다스에서 분위수 값 계산
ns_book7['대출건수'].quantile(0.25)

np.float64(3.0)

In [ ]:
#quantile() 메서드에 여러 개의 분위수를 지정할 수도 있음
ns_book7['대출건수'].quantile([0.25, 0.5, 0.75])

#결과 : 여러 개의 분위수를 지정하면 각 분위수에 해당하는 값을 담은 시리즈 객체를 반환함

0.25     3.0
0.50     7.0
0.75    16.0
Name: 대출건수, dtype: float64

In [ ]:
#1,2,3,4,5 다섯 개의 숫자가 있을 때 90% 위치에 있는 값은?
pd.Series([1,2,3,4,5]).quantile(0.9) #시리즈 객체를 정의한 후 분위수를 구함

#이렇게 두 지점 사이에 놓인 특정 위치의 값을 구하는 방법을 '보간'이라고 부름

np.float64(4.6)

In [ ]:
'''
설명
<quantile() 메서드>
- interpolation 매개변수에서 중간 값을 계산하는 방법을 결정함
* 만약 interpolation 매개변수를 따로 지정하지 않으면 기본값으로 계산됨 (기본값:linear/양쪽 분위수에 비례하여 결정됨)

<interpolation 매개변수의 또 다른 보간 방식>
pd.Series([1,2,3,4,5]).quantile(0.9, interpolation='midpoint')
 ㄴ여기서 midpoint는 분위수에 상관없이 무조건 두 수 사의 중앙값을 사용함

 pd.Series([1,2,3,4,5]).quantile(0.9, interpolation='nearest')
 ㄴ두 수 중에서 가까운 값을 선택함

 ** 이거 말고도 두 수 중 작은 값을 선택하는 'lower', 큰 값을 선택하는 'higher'가 있음 **

####백분위 구하기

In [ ]:
#10이 위치한 백분위 찾기
#-'대출건수'열의 값이 10보다 작은지 비교하여 불리언 배열을 만듦
#특정 백분위수를 구할 때는 불리언 배열을 사용하여 비율을 계산함

borrow_10_flag = ns_book7['대출건수'] < 10

#이렇게 변환한 borrow_10_flag 배열에서 True인 개수를 모두 헤아린 후 전체 데이터 개수로 나누면 10보다 작은 데이터를 순서대로 놓았을 때
#10이 위치한 백분위와 거의 비슷하게됨

In [ ]:
#판다스에서 불리언 자료를 산술 연산하면 True는 1, False는 0으로 취급함

borrow_10_flag.mean()

np.float64(0.5871657059130595)

In [ ]:
#quantile() 메서드에 백분위를 넣어 직접 확인해보기
ns_book7['대출건수'].quantile(0.65)

np.float64(12.0)

####분산 구하기
-평균으로부터 데이터가 얼마나 퍼져있는지를 나타내는 통계량

In [ ]:
#var() 메서드 : 분산 계산 메서드
ns_book7['대출건수'].var()

405.3190940363954

####표준편차(s) 구하기 : 분산에 제곱근을 한 것

In [ ]:
#std() 메서드 : 표준편차 계산 메서드
ns_book7['대출건수'].std()

#해석
#-어떤 도서의 대출건수를 확인했을 때 평균보다 20만큼 더 많거나 적을 수 있다는 뜻

20.132538191604045

####최빈값 구하기

In [ ]:
#mode() 메서드 : 텍스트형과 수치형 모두 적용 가능
ns_book7['도서명'].mode()

0    승정원일기
Name: 도서명, dtype: object

In [ ]:
ns_book7['발행년도'].mode()

0    2012
Name: 발행년도, dtype: object

####데이터프레임에서 기술통계 구하기

In [ ]:
#numeric_only 매개변수 : 해당 열에만 적용하도록 True로 지정해야함
ns_book7.mean(numeric_only=True)

번호         2.337762e+05
세트 ISBN    9.788106e+12
도서권수       1.124310e+00
대출건수       1.299358e+01
dtype: float64

In [ ]:
#mode() 메서드도 데이터프레임에서 호출 가능
ns_book7.loc[:,'도서명':].mode()

#**주의** mode() 메서드 출력 결과물 사이에는 서로 연관이 없다는 것을 주의하기

,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,승정원일기,세종대왕기념사업회 [편],문학동네,2012,9788912127893,9.788937e+12,0,2,813.6,1,0,1970-01-01

In [ ]:
ns_book7.to_csv('ns_book7.csv', index=False)

####넘파이의 기술통계 함수

####평균 구하기(mean()함수, average()함수)

In [ ]:
#mean() 함수
import numpy as np
np.mean(ns_book7['대출건수'])     # 판다스와 동일

np.float64(12.993583525073317)

In [ ]:
#average() 함수
# - 기본적으로 mean()함수와 동일하게 평균을 계산하는데, weights 매개변수에 가중치를 제공하면 가중 평균을 계산함
#가중평균? : 평균을 구할 때 각 값의 중요도에 따라 가중치를 부여하여 계산하는 평균
# - 평균할 값에 각각의 가중치를 곱하고 전체 가중치로 나누어 계산함


#average() 함수로 평균 구하기(weight기준 : 도서권수의 역수로 지정)
np.average(ns_book7['대출건수'], weights=1/ns_book7['도서권수'])

np.float64(12.044504244280425)

####1/ns_book7['도서권수'] 가 어떻게 계산되는걸까?
-'브로드캐스팅' = 판다스 데이터프레임과 시리즈 객체에 스칼라 값으로 산술 연산을 수행하면 모든 원소에 연산이 동일하게 적용되는 과정을 통해 계산됨.

In [ ]:
#대출건수 열을 도서권수 열로 나누어 도서권수가 1일 때 대출건수를 얻기
np.mean(ns_book7['대출건수']/ns_book7['도서권수'])

#결과 : 모든 도서권수가 1이기 때문에 도서권수에 따라 대출건수에 미치는 영향을 덜 받아 기존 평균값 보다 낮아지게 됨

np.float64(11.392127814996497)

In [ ]:
#도서에 상관없이 한 권 당 대출건수 평균 구하기
ns_book7['대출건수'].sum()/ns_book7['도서권수'].sum()

np.float64(11.55693781048428)

####중앙값 구하기

In [ ]:
#median() 함수
np.median(ns_book7['대출건수'])    #판다스와 동일

np.float64(7.0)

####최솟값, 최댓값 구하기

In [ ]:
#min() 함수
np.min(ns_book7['대출건수'])

0

In [ ]:
#max() 함수
np.max(ns_book7['대출건수'])

2287

####분위수 구하기

In [ ]:
#quantile() 함수
#대출건수 열의 사분위수 찾기
np.quantile(ns_book7['대출건수'],[0.25, 0.5, 0.75])

#넘파이는 percentile() 함수도 제공함. 마찬가지로 분위수를 구할 수 있음. 백분위를 0~100 사이의 값으로 지정하는 것 외에는 quantile() 함수와 동일함

array([ 3.,  7., 16.])

####분산 구하기

In [ ]:
#var() 함수 제공
np.var(ns_book7['대출건수'])        #판다스와 다름(-> n-1 자유도 때문)

405.3181859638381

####**n-1 자유도**
-표본집단은 평균과 n-1개의 샘플 데이터를 알고 있다면 마지막 한 개의 샘플 값은 자동으로 알 수 있음. 이러한 경우를 자유도 n-1 이라고 함. 따라서 분산을 계산할 때 분모를 n이 아니라 n-1로 나눔

**이렇게 기억하자**

####판다스
-판다스 var()메서드의 ddof 매개변수 기본값은 1이므로 n-1로 나눗셈
####넘파이
-넘파이 var()메서드의 ddof 매개변수 기본값은 0이므로 n으로 나눗셈

In [ ]:
#판다스
ns_book7['대출건수'].var(ddof=0)

405.3181859638381

In [ ]:
#넘파이
np.var(ns_book7['대출건수'], ddof=1)

405.3190940363954

####표준편차 구하기

In [ ]:
#std() 함수
np.std(ns_book7['대출건수'])

20.13251563922994

####최빈값 구하기

In [ ]:
#넘파이는 직접적으로 최빈값을 계산하는 함수를 제공하지 않음
#unique() 함수를 사용해 최빈값을 찾을 수 있음

#unique() 함수 : 배열에서 고유한 값을 찾아줌
#return_counts 매개변수 : 기본값 False에서 True로 바꿔 주면 고유한 값의 등장 횟수도 반환함

#먼저 unique() 함수를 호출해 고유한 값(values)와 등장 횟수(counts) 배열을 얻음
values, counts = np.unique(ns_book7['도서명'], return_counts=True)

#argmax() 함수 : 이 함수를 사용해 counts 배열에서 가장 큰 값의 인덱스 찾기
max_idx = np.argmax(counts)

#values 배열에서 해당 인덱스의 값을 출력함
values[max_idx]

'승정원일기'